### ISSUE TITLE
Restart from a given step number

### ISSUE THREAD

**Issue by mbusato0** [korintje/dftbplus_restarter#1]
Dear authors,

thank you very much for the useful tool. I was wondering if there is a way to restart from a given step number (not the last one). I tried the --max-iter option but with poor results.
This is usually needed because in NVT runs also the data about the thermostat must be restarted, which are contained in the md.out file. However, the program writes this file after the geo_end.xyz one, so that if the run crashes for some reason (e.g., exceeded wall time), one cannot restart from the last step written in the trajectory file, but must select the last step for which the thermostat parameters have been written. 
Also, adding a restart function for the thermostat in the python script would be very useful.

Thank you in advance.
Regards,
mbusato

**Comment by korintje** [comment]
Thank you for the suggestion. It sounds useful.

So, I have already finished newly implementing "--restart-from" (or shortly "-f") option in the other branch (https://github.com/korintje/dftbplus_restarter/tree/from_iter). You can restart from a specified MD step number. 
I will merge this branch into the main branch after checking and fixing bugs.

Adding a restart function for the thermostat also sounds useful.
I am not yet familiar with thermostat function, so I will work with it later.

**Comment by mbusato0** [comment]
Thank you very much indeed for the new implementation.

I've already struggled with the thermostat restart, it deals with adding the x, v, and g values to the "Thermostat" section in the input file. These values are found in the md.out file and of course must correspond to the coordinates and velocities of the atoms (they should all come from the same step). In the input file this section will look like:

Driver = VelocityVerlet{
 TimeStep [fs] = 1.0
  Thermostat = NoseHoover {
    Temperature [Kelvin] = 300
	Restart{
	        x{0.5351263186E+00   -0.1683933163E+02    0.1823564082E+03}
			v{-0.1247999924E-04    0.1478896869E-02    0.2247293460E-04}
			g{-0.1334724571E-06   -0.5074570642E-05   -0.3197689450E-05}
			}
    CouplingStrength [cm^-1] = 3200
  }

Don't hesitate to ask if you need further information. Let's collaborate on this.

Regards

**Comment by mbusato0** [comment]
Also, I've noticed that in the old version of the code, in the new input file the geometry was written according to the GenFormat. For example, I had this result for a 3D-periodic system of 665 atoms and 18.5101 A side length:

Geometry {
  GenFormat {
    665 S
    C O H
    1 1 0.1508791903E+02 0.3842203844E+01 0.9162497137E+00
    2 1 0.1489734234E+02 0.5363895925E+01 0.1045698141E+01
    3 1 0.1342566715E+02 0.5686208050E+01 0.1636961387E+01
    4 1 0.1235272558E+02 0.4854020507E+01 0.9604228264E+00
    5 1 0.1272165799E+02 0.3414371107E+01 0.7743700275E+00
.
.
.
    665 3 0.1642804172E+02 0.7523520993E+01 0.7360058959E+01
    0.0000000000E+00 0.0000000000E+00 0.0000000000E+00
    0.1851010000E+02 0.0000000000E+00 0.0000000000E+00
    0.0000000000E+00 0.1851010000E+02 0.0000000000E+00
    0.0000000000E+00 0.0000000000E+00 0.1851010000E+02
  }
}

While in the new version of the code the geometry is written to the new input file in the following format:

Geometry {
  TypeNames = C O H
  Periodic = Yes
  LatticeVectors [Angstrom] {
    18.5101 0.0 0.0
    0.0 18.5101 0.0
    0.0 0.0 18.5101
  }
  TypesAndCoordinates {
    1 15.09796347 3.87722616 0.89361024
    1 14.90850386 5.3202212 1.08001303
    1 13.50967986 5.6988516 1.56821221
    1 12.33696331 4.8654968 0.98008411
    1 12.68564885 3.39477697 0.79703517
.
.
.
    3 14.65299416 7.31233867 7.67876492
    3 16.36719357 7.61173224 7.50394164
  }
}

Would you say that the two forms are equivalent?

Thank you very much in advance.

**Comment by korintje** [comment]
Thank you for explaining how to deal with thermostat restart.
I think I have understood what to do next.

> Would you say that the two forms are equivalent?

Yes. In my understanding, these two are equivalent and the later is more explicit.

**Comment by korintje** [comment]
~~The 4th column of `geo_end.xyz` records simple Mulliken valence of each atom at each step.However, they do not contain orbital-resolved information (as stored in `charges.bin` or `charges.dat`), which is needed to restart MD.~~

~~Therefore, now I suspect that restarting from a step which is not the last seems to be impossible, excepting some specific cases (e.g., fully closed shells).~~

**Comment by korintje** [comment]
@mbusato0 
Sorry for the late response.
I have enabled thermostat restart as merged in the above PR.
Thank you for your kind suggestions.
