### ISSUE TITLE
Nose-Hoover with MDRestartFrequency > 1

### ISSUE THREAD

**Issue by bhourahine** [korintje/dftbplus_restarter#5]
Hello,

If this thermostat is not written at every iteration:

MDRestartFrequency = 2

there is a problem with:

 66, in load_thermostat
    iter_lines = iter_lines_list[self.iter_num]
IndexError: list index out of range

**Comment by korintje** [comment]
Thanks for the report. 
I have fixed the bug in the commit https://github.com/korintje/dftbplus_restarter/commit/948441744a1521ff305c4cd457c0d6ec01717c3d and https://github.com/korintje/dftbplus_restarter/commit/11fabad686a8733961391d22cc833121d62bcb85

---
Tested:
- Normal case (MDRestartFrequency = 7)
  - [x] `python3 restart_filemaker.py`
  - [x] `python3 restart_filemaker.py -f 28`
  - [x] `python3 restart_filemaker.py -f 27`

- Interrupted case (Total MD steps of geo_end.xyz and md.out are inconsistent)
  - [x] `python3 restart_filemaker.py`
  - [x] `python3 restart_filemaker.py -f 28` 
  - [x] `python3 restart_filemaker.py -f 27`
 
- Corrupted md.out case (All of the following cases are treated as error. )
  - [x] md.out is not found
  - [x] md.out is blank 
  - [x] md.out lacks parameters for Nose-Hoover thermostat.

**Comment by bhourahine** [comment]
Thanks, this seems to be fixed.
