### ISSUE TITLE
Removing comment strings from hsd

### ISSUE THREAD

**Issue by bhourahine** [korintje/dftbplus_restarter#6]
There is a problem reading the dftb_in.hsd template in restart_filemaker.py when there are comments in certain hsd blocks. For example:

Geometry = GenFormat {
  <<< my_file # this is a comment
}

As the script will then try to read the file "my_file # this is a comment" instead of "my_file". It's not clear to me whether this is best solved in the hsd library or the script.

**Comment by korintje** [comment]
Thank you for your report.

I have confirmed that placing the comment in a specific location in `dftb_in.hsd` causes the issue you pointed out.
Just calling `hsd.load(HSD_FILENAME)` like the following short script causes the error.
```
import hsd
hsdinput = hsd.load("dftb_in.hsd")
```

Therefore, I suppose there is nothing I can do on the script side so far. 
I think we need to fix the hsd library.

**Comment by bhourahine** [comment]
I've raised an issue on the library side at:
https://github.com/dftbplus/hsd-python/issues/27
